application:
  port: 5000

database:
  protocol: "postgres"
  host: "localhost"
  username: "postgres"
  password: "password"
  database_name: "book_catalog"

search:
  url: "http://127.0.0.1:9200"
  books_index_name: "pg.public.books"
  authors_index_name: "pg.public.authors"

redis:
  url: redis://127.0.0.1:6379

s3:
  access_key: accesskey
  secret_key: secretkey
  region: us-east-1
  endpoint: http://localhost:9000
  name: book-catalog