application:
  port: 5000

services:
  book_catalog:
    name: "book catalog"
    url: "http://book-catalog:8080"

  ratings:
    name: "ratings service"
    url: "http://ratings-service:8080"

auth:
  url: "http://auth-service:5000"

redis:
  url: "redis://localhost:6379"